<?php


/**
 * Implements hook_theme().
 */
function appointment_theme() {
  return [
    'agency_card' => [
      'variables' => [
        'agency' => NULL,
        'agency_id' => NULL,
      ],
      'template' => 'agency-card',
    ],
    'appointment_type_card' => [
      'variables' => [
        'appointment_type' => NULL,
        'appointment_type_id' => NULL,
        'appointment_type_name' => NULL,
        'image_path' => NULL,
      ],
      'template' => 'appointment-type-card',
    ],
    'advisor_card' => [
      'variables' => [
        'advisor' => NULL,
        'advisor_id' => NULL,
        'image_path' => NULL,
      ],
      'template' => 'advisor-card',
    ],
    'personal_information' => [
      'variables' => [
        'appointment_details' => NULL,
        'form' => NULL,
        'image_path' => NULL,
      ],
      'template' => 'personal-information',
    ],
    'confirm_information' => [
      'variables' => [
        'appointment_details_confirmation' => [],
      ],
      'template' => 'confirm-information',
    ],
    'appointment_confirmation_message' => [
      'variables' => [
        'image_path' => '',
        'title' => '',
        'message' => '',
        'change_button' => [],
      ],
      'template' => 'appointment-confirmation-message',
    ],

  ];
}
